export const REPOSITORIES_TOKEN = {
  USER_REPOSITORY_TOKEN: Symbol.for("USER_REPOSITORY_TOKEN"),
  AUDIT_REPOSITORY_TOKEN: Symbol.for("AUDIT_REPOSITORY_TOKEN"),
  PROFILE_REPOSITORY_TOKEN: Symbol.for("PROFILE_REPOSITORY_TOKEN"),
} as const;
